--- lsp.lua
--- $ figlet -f larry3d theovim
---  __    __
--- /\ \__/\ \                              __
--- \ \ ,_\ \ \___      __    ___   __  __ /\_\    ___ ___
---  \ \ \/\ \  _ `\  /'__`\ / __`\/\ \/\ \\/\ \ /' __` __`\
---   \ \ \_\ \ \ \ \/\  __//\ \L\ \ \ \_/ |\ \ \/\ \/\ \/\ \
---    \ \__\\ \_\ \_\ \____\ \____/\ \___/  \ \_\ \_\ \_\ \_\
---     \/__/ \/_/\/_/\/____/\/___/  \/__/    \/_/\/_/\/_/\/_/
---
--- Configuration for:
--- - Neovim built-in diagnostic framework
--- - Neovim built-in LSP engine enabled by
---   - lspconfig
---   - Mason
---   - Mason-lspconfig
--- - Neovim built-in completion engine enabled by
---   - nvim-cmp
---   - Luasnip
---
